### PR TITLE
feat: Add Tracing

### PR DESCRIPTION
**Pull request by HazAT**
# Installation

Read
https://docs.sentry.io/performance-monitoring/performance/
to understand the concept behind Tracing/Performance in Sentry.

Make sure you have following in you `composer.json`

```json
"require": {
        "sentry/sentry-laravel": "dev-performance/beta"
},
"minimum-stability": "dev",
"prefer-stable": true,
```

After that run `composer update`.

Make sure the installation of `sentry/sentry`, `sentry/sdk` and `sentry/sentry-laravel` in the output looks something like this:

```bash
 - Installing sentry/sentry (3.x-dev dd6ef34)
 - Installing sentry/sdk (3.x-dev f6b434e)
 - Installing sentry/sentry-laravel (dev-performance/beta 745bd72)
```

The important part is that both `sentry/sentry` and `sentry/sdk` are `3.x` where `sentry/sentry-laravel` is `dev-performance/beta`.

After that add `'traces_sample_rate' => 1.0,` to the file in `config/sentry.php`.
Note that the value should be larger than `0.0` and smaller or equal than `1.0` (to send everything).
More info can be found here: https://docs.sentry.io/performance-monitoring/getting-started/

## Connecting your frontend

To setup tracing for your Vue frontend, follow: https://docs.sentry.io/performance-monitoring/getting-started/?platform=vue

An additional step you should take is, add this to your blade template rendering the `<head>` tag  `{!! Sentry\Laravel\Integration::sentryTracingMeta() !!}`
This adds a meta tag similar to `<meta name="sentry-trace" content="ae02a316231d490c870b14f27aba8d29-c4a72ffd39444c84-1"/>` to your header and tells the frontend code to pick up the trace.

*Known Issues*

- Right now we are not using an agent to send those transactions meaning Laravel sends the Transactions after finishing serving the request but the process is only terminated once the Transaction is sent. It shouldn't impact your users a lot but something to keep in mind.
- If you are using on-premise you need to make sure to use the latest release of Sentry https://github.com/getsentry/sentry/releases/tag/20.6.0 or master. Transactions hit a new endpoint and can only be received there. 

### Papertrail

- [x] Record sql queries as spans
- [x] Record rendered views as spans
- [x] Get route name like `/users/{id}` instead of `/users/1`
- [x] Start Transaction from incoming headers
- [ ] Collect query span regardless of `sentry.breadcrumbs.sql_queries` option?

This works together with https://github.com/getsentry/sentry-php/pull/1031

Resulting in:

image

### CODE REVIEW

**Comment by dmyers** [comment]
I was just reading about this today on Sentry’s docs and was hoping PHP and Laravel would be added as the docs just have Python and JavaScript. This would be fantastic!

**Comment by HazAT** [comment]
@dmyers Yes PHP/Laravel will be supported next :) 

That's a good point, maybe we should finish the transaction in `terminate`.
If you have more input or idea how and what to measure feel free to comment / help :) 
(Updated the screenshot)

I was also trying to measure/instrument the 217ms gap but I am not sure what's causing this. It's not the middleware, I guess the ServiceProviders but not sure how to measure them.

**Comment by HazAT** [comment]
@markstaun Thanks for the feedback, we'll fix this.

**Comment by markstaun** [comment]
Sounds great, really looking forward to deploying this to production!

**Comment by Josh-G** [comment]
if you aren't seeing `view.render` spans; we had to add `sentry/sentry-laravel` to our `dont-discover` array as other service providers were resolving `view.engine.resolver` prior to the Tracing service provider being registered. To resolve, we manually corrected the service provider order in our config.

alternatively, Sentry could check if the view engine resolver has already been resolved in `register` (`$this->app->resolved('view.engine.resolver')`)

other than that, it works quite well for us, providing insight into our slowest rendering views 👍

**Comment by stayallive** [comment]
@Josh-G good one thanks for letting us know, could you show me a package that resolves the view engine so I can test with working around that? Having a hard time coming up with one.

@markstaun I believe the issue in testing should be fixed!

**Comment by Josh-G** [comment]
> could you show me a package that resolves the view engine

@stayallive One of the two service providers in [`hyn/multi-tenant`](https://github.com/tenancy/multi-tenant) ends up resolving the view engine (I didn't go as far as to determine exactly which provider, just the package that was conflicting).

**Comment by stayallive** [comment]
@Josh-G, thanks, I'll figure it out from here, I'll let you know once it's fixed 👍

**Comment by stayallive** [comment]
Actually @Josh-G, I think I already got it, let me know how this works for you!

**Comment by Josh-G** [comment]
@stayallive Perfect, thanks! Have tested and no longer requires a specific service provider order :) works out of the box

**Comment by archon810** [comment]
Anything special that is needed to get this to work for WordPress?

**Comment by stayallive** [comment]
This code is specific to Laravel and will not work for any other platform.

The PHP SDK is currently in the works to get all tracing related code integrated (getsentry/sentry-php#1031) and once that is stable other integrations could start implementing it. This L

To instrument WordPress the WordPress integration will need to write a similar kind of code hooking into parts of WordPress to get some meaningful tracing information.

**Comment by archon810** [comment]
@stayallive Should I start a ticket for that or is official WordPress PHP Tracing/Performance support not expected?

**Comment by stayallive** [comment]
@archon810 you are ofcourse free to open a ticket to track the interest but the WordPress integration is technically not an official integration while PHP, Laravel (and Symfony) are so it might take a bit longer.

**Comment by markstaun** [comment]
Just tested this branch again with our codebase, but some of our tests are failing.

```
1) Tests\Feature\Admin\AdminLoginTest::testSystemAdminCantAccessShops
Sentry\Exception\EventCreationException: Unable to instantiate an event

/Users/user/code/laravel/vendor/sentry/sentry/src/EventFactory.php:114
/Users/user/code/laravel/vendor/sentry/sentry/src/Client.php:184
/Users/user/code/laravel/vendor/sentry/sentry/src/Client.php:112
/Users/user/code/laravel/vendor/sentry/sentry/src/Client.php:104
/Users/user/code/laravel/vendor/sentry/sentry/src/State/Hub.php:134
/Users/user/code/laravel/app/Exceptions/Handler.php:78
/Users/user/code/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:403
/Users/user/code/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:111
/Users/user/code/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php:508
/Users/user/code/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php:292
/Users/user/code/laravel/tests/Feature/Admin/AdminLoginTest.php:37
```

And here is the actual exception that is catched in the EventFactory.php:114.

```
1) Tests\Feature\Admin\AdminLoginTest::testSystemAdminCantAccessShops
ReflectionException: Method Illuminate\Pipeline\Pipeline::__call() does not exist

/Users/user/code/laravel/vendor/sentry/sentry/src/FrameBuilder.php:178
/Users/user/code/laravel/vendor/sentry/sentry/src/FrameBuilder.php:87
/Users/user/code/laravel/vendor/sentry/sentry/src/StacktraceBuilder.php:66
/Users/user/code/laravel/vendor/sentry/sentry/src/StacktraceBuilder.php:46
/Users/user/code/laravel/vendor/sentry/sentry/src/EventFactory.php:147
/Users/user/code/laravel/vendor/sentry/sentry/src/EventFactory.php:102
/Users/user/code/laravel/vendor/sentry/sentry/src/Client.php:184
/Users/user/code/laravel/vendor/sentry/sentry/src/Client.php:112
/Users/user/code/laravel/vendor/sentry/sentry/src/Client.php:104
/Users/user/code/laravel/vendor/sentry/sentry/src/State/Hub.php:134
/Users/user/code/laravel/app/Exceptions/Handler.php:78
/Users/user/code/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:403
/Users/user/code/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:111
/Users/user/code/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php:508
/Users/user/code/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php:292
/Users/user/code/laravel/tests/Feature/Admin/AdminLoginTest.php:37
```

**Comment by HazAT** [comment]
@markstaun I fixed this in the latest commit in PHP repo https://github.com/getsentry/sentry-php/commit/67f15ce3af1f2e7316fa891be68d8ad315f674d0

**Comment by markstaun** [comment]
Thanks, I can confirm that it's working and all our tests are now passing 👌

**Pull request merged**
