### PR TITLE
Add Laravel Octane support, fixes #479

### LINKED ISSUE #479: Adding support for Laravel Octane?
It looks like if we're running the web server using a long running process mechanism like **Laravel's Octane** or other packages like `spiral/roadrunner-laravel` or `php-pm/php-pm` or `swooletw/laravel-swoole` the events do not get flushed unless the workers are restarted and also cause issues with scoping each individual requests since the cleaning up and flushing of events aren't being called after each request like how it's handled for job queues.

As Laravel now has an official package (currently in public beta), it would be great if Sentry adds this mechanism for HTTP requests as Octane has the potential to go big.

### PR DESCRIPTION
**Pull request by tm1000**
This adds support for Octane Listeners so that Sentry is reset (scopes) correctly between request, ticks and tasks as part of Laravel's Octane (https://laravel.com/docs/8.x/octane).

I followed how Queues were detected and reset and tested afterwards.

Additionally this will fix #479 (and confirmed that #475 fixes pushing of events in long running processes like Octane!) 

Some things to note:

- I'm not sure if breadcrumbs should be added for RequestReceived since it probably should act like a route (I mean it is..) additionally the route is properly labeled here like in non Octane land. For consistency sake I added breadcrumbs but they are rather useless
image
- Breadcrumbs on Tasks (https://laravel.com/docs/8.x/octane#concurrent-tasks) and Ticks (https://laravel.com/docs/8.x/octane#ticks-and-intervals) are also kind of useless because on Ticks there's nothing to really breadcrumb (like there is on queues) additionally on tasks you can breadcrumb $data but $data is mixed which makes it harder to deal with, unless you generically transform it, probably not worth the hassle (if end user wants to do this then they can on their end)
- Unsure what to do with RequestHandled (https://github.com/laravel/octane/blob/722b7567e2817b3f5e4a4ae7b49290f53968a114/src/ApplicationGateway.php#L37). It appears this is only hit if there is no route defined for said request. 
- I did not handle anything in regards to WorkerStarting (same as the already existing Queues code)

### CODE REVIEW

**Comment by tm1000** [comment]
@stayallive requesting review

**Comment by stayallive** [comment]
@tm1000 a little patience please it's been 2 days 😎

Feel free to use this branch in the meantime to test it out of course (which I'm sure you are already doing) but I'll need some time to look this over and test it to make sure everything is working as intended.

**Comment by stayallive** [comment]
I have pushed a few changes to cleanup a bit and test it out myself, lot's of things needed a little attention especially regarding container being injected in constructors which is unfortunate.

I am not convinced that this is working as intended yet and I would greatly appreciate any help testing this code out to see if this is correctly doing what it should.

**Comment by tm1000** [comment]
@stayallive Oh shoot I totally forgot about the container issues that arise as a result of Octane itself (long running). 

I have code that is already using my branch and since your commits go against that I'll be able to continue testing.

**Comment by stayallive** [comment]
To make it easy for every to test out I've duplicated the branch to this repo, you can try it out by changing this `sentry/sentry-laravel` dependency in your `composer.json` and running `composer update` to pull in this PR and give it a test:

```diff
-   "sentry/sentry-laravel": "^2.7"
+   "sentry/sentry-laravel": "dev-feature/laravel-octane-support as 2.8"
```

**Comment by DeepDiver1975** [comment]
Just gave this a quick test - looks good from here! THX a lot!

**Comment by stayallive** [comment]
So this all seems to be working OK so far, so let's release it 👍 

If any more issues arrise or edge cases are found please create a new issue/PR so we can fix it!

Thanks everyone for your contributions/testing/thoughts!

**Comment by tm1000** [comment]
Thank you @stayallive for your support!

**Pull request merged**
