### PR TITLE
Added support for Laravel 5.7

### PR DESCRIPTION
**Pull request by janyksteenbeek**
Laravel just released its newest major version update, Laravel 5.7. This pull request adds support for Laravel 5.7.

https://laravel.com/docs/5.7/releases#laravel-5.7

### CODE REVIEW

**Comment by stayallive** [comment]
Hey @janyksteenbeek, thanks but someone was quicker, see: #148.

Release will be tagged in a bit.

**Comment by stayallive** [comment]
@janyksteenbeek also you are jumping the gun... it's not tagged yet!

See: https://github.com/laravel/framework/tags

**Comment by aocneanu** [comment]
Was this merged? 5.7 is live:)

**Comment by stayallive** [comment]
@aocneanu see: #148.

**Pull request closed without merging**
