### PR TITLE
Improve breadcrumbs

### PR DESCRIPTION
**Pull request by dcramer**
- capture illuminate queries
- swap monolog for illuminate log

This change is [Reviewable](https://reviewable.io/reviews/getsentry/sentry-laravel/31)

### CODE REVIEW

**Comment by dcramer** [comment]
@taylorotwell part of me was hoping to blindly capture all events, but it seems in some cases the Event has a string defining it (which is great!) and others its a class name (which is less great). Have you considered requiring consistency in event names in a future version?

**Comment by dcramer** [comment]
@stayallive this seem sane to you? seems good in both 4 and 5. I'm not sure if theres other situations or very common events we should capture here.

**Comment by dcramer** [comment]
And finally, interestingly in Laravel 4 illuminate.log seems like it might be better for us than Monolog:

screenshot 2016-09-27 13 35 07

**Comment by stayallive** [comment]
@dcramer Going to check this out in a few hours when I wake up :)

**Comment by stayallive** [comment]
@dcramer if you would like you can do something like the debugbar does with capturing all the events although I'm not sure if usefull (https://github.com/barryvdh/laravel-debugbar/blob/master/src/DataCollector/EventCollector.php). The other collectors in the debugbar source are also very interesting and might give you some ideas on what to collect.

Few that I can think of would be usefull are:
- `Illuminate\Routing\Events\RouteMatched`: To see which route is hit
- `Illuminate\Mail\Events\MessageSending`: See which mails are dispatched
- `Illuminate\Queue\Events\*`: This might be a bad idea in <= 5.2 because there the queue worker process runs indefinitly so they amount of event buildup would be crazy (seeing 100+ breadcrumbs already on queue jobs in a 5.2).

I looked in this list: https://laravel.com/docs/5.1/events#framework-events. These are almost all changed to use classes in 5.2+ but might give you an idea on what's there and what the framework emits. You can find event classes quickly by looking in the `vendor/illuminate/*/Events/*` folders.

I personally would like to be able to configure the level or verbosity these loggings happen because this could possibly be a overhead that is not worth it on every environment. I could imagine this could lead to memory problems and extremely large requests sent to Sentry with hundreds of breadcrumbs with large datasets (queries and or bindings).

Hope this is usefull 👍

**Comment by dcramer** [comment]
@stayallive def makes sense -- maybe we'll bring along configuration similar to Laravel, in that you can specify either listeners to include or create a blocklist of ones you dont want. I will take a look at the debugbar implementation, as I agree some of these could be useful.

**Comment by dcramer** [comment]
@stayallive only doing logs/queries for now, but i greatly improved it inspired by debugbar

**Comment by stayallive** [comment]
@dcramer this looks very nice indeed 👍

**Comment by dcramer** [comment]
Adding lumen support (if doable) and then gonna merge + release.

**Comment by dcramer** [comment]
screenshot 2016-09-29 13 18 34

**Comment by stayallive** [comment]
Lumen is using the same components for database and events as Laravel does so it should be very straight forward. 

Looking at that screenshot I already can see this is going to be a very usefull addition. Sometimes looking at data in objects where I can only see the classnames, with this I will be able to tell what I'm actually looking at 💯

**Comment by dcramer** [comment]
@stayallive appears like the events may not exist by default in Lumen (at least struggling to get breadcrumbs showing up)

**Comment by stayallive** [comment]
@dcramer do you have this uncommented? Might not register correctly otherwise. https://github.com/getsentry/sentry-laravel/blob/master/examples/lumen-5.2/bootstrap/app.php#L28

Although looking at the source, as long as events is bound all should work just fine. https://github.com/illuminate/database/blob/master/DatabaseManager.php#L189

Going to try get this working too... should be the same as Laravel I thought...

**Comment by dcramer** [comment]
@stayallive nope but that doesnt seem to change it

**Comment by stayallive** [comment]
Works for me, did you change your test config to actually log the queries (`config/sentry.php`)? 😜 

screen shot 2016-09-29 at 23 19 02

**Comment by dcramer** [comment]
@stayallive well its just for logging bindings (queries will always log atm), but if it works for you I'm content :)

**Comment by stayallive** [comment]
Yes even with Eloquent off it works like a charm 👍

**Comment by dcramer** [comment]
This is now available in 0.4.0

**Comment by stayallive** [comment]
Going to push this to prod right now, the transaction tracing also looks sweet!

**Pull request merged**
