### PR TITLE
Fix test class namespaces

### PR DESCRIPTION
**Pull request by spawnia**
Fixes the namespaces of test classes to conform with PSR-4.

### CODE REVIEW

**Comment by stayallive** [comment]
Test suite is not liking this change.

**Comment by spawnia** [comment]
> Test suite is not liking this change.

I rebased atop the latest `master`. It seems like only some versions are failing, I don't really get why. Do you have an idea what could be going on?

**Comment by spawnia** [comment]
Found and fixed the reason for the failing tests.

**Review by stayallive — APPROVED** [review]
Cool, appreciate it, thanks!

**Pull request merged**
