### PR TITLE
Adjust README.me with how to setup Laravel Logging

### PR DESCRIPTION
**Pull request by sakalauskas**
I think it's worth putting this into README.md as It took me some time until I found how to set-up the logging.

Kudos to @AidasK in #34

### CODE REVIEW

**Comment by AidasK** [comment]
```php

        \Log::listen(function ($level, $message, $context) {
            switch ($level) {
                case 'debug':
                    $level = 'info';
                    break;
                case 'critical':
                    $level = 'error';
            }
            $context['level'] = $level;
            if ($message instanceof \Exception) {
                app('sentry')->captureException($message, [], $context);
            } else {
                app('sentry')->captureMessage($message, [], $context);
            }
        });
```

This is my current code block. I haven't checked if all laravel and sentry error levels are mapped. 
These are all possible values in raven:
    const DEBUG = 'debug';
    const INFO = 'info';
    const WARN = 'warning';
    const WARNING = 'warning';
    const ERROR = 'error';
    const FATAL = 'fatal';
And these are in Laravel:
        'debug'     => MonologLogger::DEBUG,
        'info'      => MonologLogger::INFO,
        'notice'    => MonologLogger::NOTICE,
        'warning'   => MonologLogger::WARNING,
        'error'     => MonologLogger::ERROR,
        'critical'  => MonologLogger::CRITICAL,
        'alert'     => MonologLogger::ALERT,
        'emergency' => MonologLogger::EMERGENCY,

debug, critical,notice,alert,emergency should be mapped as well.

In the use case, I would include tags:
```php
\Log::error('bad response code', ['tags' => ['response_code' => 404]]);
```

**Comment by sakalauskas** [comment]
@AidasK thanks, I mapped all of these now, although, the user should define these themselves e.g. to only send critical events to sentry.

**Comment by stayallive** [comment]
Quoting @dcramer I don't think we are going to add this since Sentry is not a logging tool.

> We think of Sentry as an additional thing beyond logging due to the depth it goes into. People compare it to logging because its the concept they're familiar with. It's a "log", but not traditional logging.

https://github.com/getsentry/sentry-php/issues/404#issuecomment-285525468

And quoting https://sentry.io/vs/logging/:

> To summarize, Sentry works with your application logging infrastructure, often integrating directly. It does not replace the need for those logs, and it's also not a destination for things that aren't actionable errors or crashes.

**Comment by AidasK** [comment]
```php
\Log::error('bad response code', ['tags' => ['response_code' => 404]]);
```
This looks like an error to me. Don't know why it should not be merged. I am paying for every log message and it is up to me what I am sending there.

**Comment by stayallive** [comment]
You are absolutely free to do whatever you want, that was not what I meant to say. 

The reason why IMHO it should not be merged is because this explains how to do something that is not what Sentry wants you to do persé, use Sentry as a logging tool.

It might be better to only send warning/error (and worse) levels instead of sending every event level like the PR currently suggests.

This will keep it more in the direction of logging "actionable errors or crashes".

**Comment by dcramer** [comment]
I'm not opposed to documenting this, but at the end of the day our goal is exception reporting. We *do* support capturing errors from things like logging (as "Message" events), I just try to continually enforce what the objective is so people dont conflate Sentry as being an alternative to something like ELK/Splunk/etc/etc

**Comment by ankurk91** [comment]
This package may help in logging

https://github.com/jenssegers/laravel-raven

**Comment by AidasK** [comment]
Laravel 5.5 has changed a lot.
You have to remove report method from `Handler` and add this to event service provider.
```php
        \Log::listen(function (MessageLogged $e) {
            $level = $e->level;
            switch ($level) {
                case 'debug':
                    $level = 'info';
                    break;
                case 'notice':
                case 'alert':
                    $level = 'warning';
                    break;
                case 'critical':
                    $level = 'error';
            }
            $context = $e->context;
            if (isset($context['exception'])) {
                $message = $context['exception'];
                unset($context['exception']);
            } else {
                $message = $e->message;
            }
            $context['level'] = $level;
            if ($message instanceof \Exception) {
                app('sentry')->captureException($message, [], $context);
            } else {
                app('sentry')->captureMessage($message, [], $context);
            }
        });
```

**Comment by stayallive** [comment]
With the new Laravel 5.6 logging channels this should be implemented somewhat like you wanted possibly.

> https://github.com/getsentry/sentry-laravel#using-laravel-56-log-channels

Closing this for now.

**Pull request closed without merging**
