### PR TITLE
Add more options to breadcrumbs configuration

### LINKED ISSUE #257: Options to disable SQL and log breadcrumb
We don't want to send SQL and logs to Sentry, it there a way to disable them?

### PR DESCRIPTION
**Pull request by leo108**
Fixes #257

### CODE REVIEW

**Comment by leo108** [comment]
@stayallive any feedback on the PR?

**Comment by leo108** [comment]
@stayallive Is there any chance to look at this PR?

**Comment by stayallive** [comment]
Yeah I'm really sorry for ignoring you for this long.

I don't think this is the way to go, since this does not allow us (or Laravel) to ever make changes in the event names/types we want to watch for an operation.

There are also quite some other cases where right now it's needed that the `EventHandler` is registered no matter what since otherwise events when running a queue worker might never be sent.

How about we do something like you requested in your original request. Just allow for disabling the query breadcrumbs?

We already have:

```php
    'breadcrumbs' => [
        // Capture bindings on SQL queries logged in breadcrumbs
        'sql_bindings' => true,
    ],
```

What about adding an option like for example:

```php
    'breadcrumbs' => [
        // Log SQL queries as breadcrumbs
        'queries' => true,

        // Capture bindings on SQL queries logged in breadcrumbs
        'sql_bindings' => true,
    ],
```

This way we could keep adding options to disable built-in breadcrumb features without having to have a defined list of events in the user config.

**Comment by leo108** [comment]
@stayallive Thanks for the feedback, I'll check and update my PR.

**Comment by stayallive** [comment]
Many thanks for taking the time to do that!

**Comment by leo108** [comment]
@stayallive Please check again, thanks.

**Comment by leo108** [comment]
@HazAT Can you check this PR? thanks.

**Comment by nauxliu** [comment]
I would love to see this merged. How can we move forward on this PR?

**Comment by stayallive** [comment]
@nauxliu: @HazAT was just pinged a few short hours ago to leave his review, after he is done and there are no more "problems" found it should al go pretty quick.

It's being worked on!

Thank you (both) for your patience.

**Comment by nauxliu** [comment]
Great! looks we are making a progress, Thank you all @leo108 @stayallive @HazAT

**Pull request merged**
