### PR TITLE
Normalized route names when using Lumen

### PR DESCRIPTION
**Pull request by migralito**
Hi, I found in our projects that when using Lumen, transaction names are sent "as is" in the URL. This makes the problem of many many different transactions because, for example, a /songs/{id}/play endpoint would appear as /songs/1/play, /songs/2/play, etc etc etc.
With this, we can make the transaction names to be reported as /songs/{id}/play, fixing this problem for Lumen users.

### CODE REVIEW

**Comment by migralito** [comment]
I've just seen that we can link this PR to [this issue](https://github.com/getsentry/sentry-laravel/issues/449)

**Comment by stayallive** [comment]
@migralito I needed some time to check this out.

Unfortunately I am able to break it with a route like: `{type}/user` when called with the URL: `user/user`, it results in `{type}/{type}`.

I know this is maybe a stretch but I'm sure there are some better examples to think of where this could happen.

I was also missing the route name and action that I've added back. But I'm not 100% sure about the above issue yet.

**Comment by migralito** [comment]
> @migralito I needed some time to check this out.
> 
> Unfortunately I am able to break it with a route like: `{type}/user` when called with the URL: `user/user`, it results in `{type}/{type}`.
> 
> I know this is maybe a stretch but I'm sure there are some better examples to think of where this could happen.
> 
> I was also missing the route name and action that I've added back. But I'm not 100% sure about the above issue yet.

Hi @stayallive ,
I understand that this has some drawbacks. What happens is that this is the way I found to reconstruct the URL. It might not be bulletproof, but is much much better to _maybe_ have some URLs incorrectly named than having IDs and other parameters in the operation name. Currently, the APM is just not giving us the chance of having a representation of the operation because it breaks it down to hundred, maybe thousand of transactions.
In the event of incorrectly infering the name of the transaction, or merging two different transactions into one, there's always the chance of fixing it by customizing the transaction name. Without this, customizing the transaction name is the only way to have a non-broken APM transaction set

**Comment by migralito** [comment]
Hi @stayallive 
Any other news regarding this?
Thanks

**Comment by stayallive** [comment]
Hi @migralito, apologies for this taking so long :)

I have refactored it a bit more and added tests, how does it look to you now?

**Pull request merged**
