### PR TITLE
Gracefully handle errors capturing breadcrumbs

### PR DESCRIPTION
**Pull request by dcramer**
Refs GH-40

### CODE REVIEW

**Comment by dcramer** [comment]
I'm not sure this is the best approach to logging these errors and its not something we yet do anywhere else in PHP.

**Comment by stayallive** [comment]
I have been thinking about it and I think this is the only solution for that besides reporting it to Sentry itself. Loggin it through Laravel is also not possible since that would make it loop possibly.

But looking at #40 this would result in a log entry every single request in their app right?

**Comment by pedrommone** [comment]
@stayallive Sentry only handle exception failures, right? If I'm right, its fine to `log` it back but would be nice if it send to Sentry too.

**Comment by dcramer** [comment]
@pedrommone we pick up logs in certain situations, and also use them as breadcrumbs, which means it becomes complex and could be recursive

**Comment by dcramer** [comment]
@stayallive yeah it'd hit repeatedly for #40, but our goal would also be to fix that -- this is mostly insurance

**Comment by pedrommone** [comment]
@dcramer can you MR this one and open a new issue to figure out how to log without hit repeatedly?

**Comment by dcramer** [comment]
@pedrommone you cannot avoid repeatedly logging -- they're unique requests with no global state

**Pull request merged**
