### PR TITLE
Add Feedback to Laravel example

### PR DESCRIPTION
**Pull request by dcramer**
This change is [Reviewable](https://reviewable.io/reviews/getsentry/sentry-laravel/25)

### CODE REVIEW

**Comment by dcramer** [comment]
Getting some odd behavior when doing this, and don't have time atm to figure out why/what is going on.

**Comment by stayallive** [comment]
What is the odd behavior you are experiencing?

Also if you use a blade view you should actually use the blade syntax 😉  Otherwise you should drop the `.blade` from the filename.

Here the code with blade tags.

```blade
@unless(empty($sentryID))
    <!-- Sentry JS SDK 2.1.+ required -->
    <script src="https://cdn.ravenjs.com/3.3.0/raven.min.js"></script>
    <script>
        Raven.showReportDialog({
            eventId: '{{ $sentryID }}',

            // use the public DSN (dont include your secret!)
            dsn: 'https://e9ebbd88548a441288393c457ec90441@app.getsentry.com/3235',
            
            user: {
                'name':  'Jane Doe',
                'email': 'jane.doe@example.com',
            }
        });
    </script>
@endunless
```

**Comment by dcramer** [comment]
``php artisan clear-compiled`` seems to have resolved it

**Comment by dcramer** [comment]
@stayallive https://blog.getsentry.com/2016/07/29/user-feedback-in-laravel.html

weirdly in my test env I see the a duplicated error message, but I'm pretty sure we've got the implementation 'correct'. lmk if you have thoughts otherwise

**Comment by stayallive** [comment]
@dcramer: Freshly installed and configured the L5.2 example and it works flawless (also looks almost identical to how I am running it in production for several apps)!

The example in the blogpost is missing the `eventId: {{ $sentryID }},` in the blade example (set to empty string there).

**Comment by dcramer** [comment]
Doh, Jekyll template is evaluating the block, thanks!

**Pull request merged**
