### PR TITLE
added laravel 5.7 to list

### PR DESCRIPTION
**Pull request by OwenMelbz**
Adds the ability to use it with 5.7

### CODE REVIEW

**Comment by stayallive** [comment]
Thanks. But this is not merged until 5.7 is released and we can test it on the release version. 👍

**Comment by OwenMelbz** [comment]
@stayallive sorry I thought it had!

We were chasing a mailgun bug which was said to be fixed in 5.7 - and noticed the Laravel docs are all updated to 5.7 now the git branch was public so assumed it had, thought it was weird that it got by without me seeing xD

**Comment by stayallive** [comment]
Yeah that usually goes up a bit before the release (you had me scared I missed it too haha) :) 

When it’s tagged (https://github.com/laravel/framework/tags) it will be tested and released with the 5.7 compat quickly 😎

**Comment by patrickbrouwers** [comment]
It's perhaps can idea to merge it to a dev branch without a tag, so people can already start testing it. That way you can receive feedback before it's released and have a release ready at Laravel release day :)

**Comment by stayallive** [comment]
@patrickbrouwers good idea, I added the `laravel-57` so you should be able to use `"sentry/sentry-laravel": "dev-laravel57@dev"` in your `composer.json`, will be merged to master and tagged when 5.7 is released ofcourse.

**Comment by patrickbrouwers** [comment]
Awesome 👍

**Comment by aocneanu** [comment]
I suppose it's tagging time:)

**Pull request merged**
