### PR TITLE
Add support for laravel 8

### PR DESCRIPTION
**Pull request by dacoto97**

### CODE REVIEW

**Comment by georgeboot** [comment]
This was already attempted in #374

However, Laravel required guzzle 7 and that conflicts with the guzzle 6 adapter required by https://github.com/getsentry/sentry-php-sdk

**Comment by stayallive** [comment]
1.9.0 was released yesterday with this exact change.

**Comment by dacoto97** [comment]
@stayallive Is there any forecast of the update?

**Comment by stayallive** [comment]
@dacoto97 I'm not sure what "update" you are looking for, there are some problems with Guzzle 7 as described here: https://github.com/getsentry/sentry-laravel/issues/371#issuecomment-689084918, but assuming you've made those changes 1.9.0 will work with Laravel 8 👍

**Pull request closed without merging**
